mode: 0

mongodb:
  host: localhost:27017
  database: database
  env: native
  username: ######
  password: ######

amqp:
  url: ##################
  exchange_name: exchange_name
  exchange_type: topic
  queue_name: queue_name
