definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  schema.OutMsgCreateParam:
    properties:
      origin_code:
        example: code
        type: string
      origin_model:
        example: model
        type: string
      payload:
        type: object
      routing_key:
        example: routing.key
        type: string
    required:
    - payload
    - routing_key
    type: object
  schema.OutMsgQueryParam:
    properties:
      origin_code:
        type: string
      origin_model:
        type: string
      routing_key:
        type: string
      status:
        type: string
    type: object
  schema.OutMsgUpdateParam:
    properties:
      status:
        type: string
    type: object
  schema.RoutingCreateParam:
    properties:
      api_method:
        type: string
      api_url:
        type: string
      group:
        type: string
      name:
        type: string
      value:
        type: integer
    required:
    - api_method
    - api_url
    - group
    - name
    - value
    type: object
  schema.RoutingQueryParam:
    properties:
      group:
        type: string
      name:
        type: string
      value:
        type: integer
    type: object
  schema.RoutingUpdateParam:
    properties:
      api_method:
        type: string
      api_url:
        type: string
      group:
        type: string
      name:
        type: string
      value:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/cron/resend:
    post:
      description: api resend `failed` out messages
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: api resend failed out messages
      tags:
      - Retry
  /api/v1/cron/retry:
    post:
      description: api resend `wait retry` in messages, message will change status to
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: api retry `wait retry` in messages
      tags:
      - Retry
  /api/v1/cron/retry_previous:
    post:
      description: api resend `wait retry previous` in messages, just retry in messages
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: api retry `wait retry previous` in messages
      tags:
      - Retry
  /api/v1/out_messages:
    get:
      consumes:
      - application/json
      description: get list out messages
      parameters:
      - in: query
        name: origin_code
        type: string
      - in: query
        name: origin_model
        type: string
      - in: query
        name: routing_key
        type: string
      - in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: get list out messages
      tags:
      - Out Messages
    post:
      consumes:
      - application/json
      description: api publish out message to amqp
      parameters:
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/schema.OutMsgCreateParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: publish message to amqp
      tags:
      - Out Messages
  /api/v1/out_messages/{id}:
    put:
      consumes:
      - application/json
      description: api update out message
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: string
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/schema.OutMsgUpdateParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: api update out message
      tags:
      - Out Messages
  /api/v1/routing_keys:
    get:
      consumes:
      - application/json
      description: get list routing keys
      parameters:
      - in: query
        name: group
        type: string
      - in: query
        name: name
        type: string
      - in: query
        name: value
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: get list routing keys
      tags:
      - Routing Keys
    post:
      consumes:
      - application/json
      description: api create routing key
      parameters:
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/schema.RoutingCreateParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: create routing key
      tags:
      - Routing Keys
  /api/v1/routing_keys/{id}:
    get:
      consumes:
      - application/json
      description: api retrieve routing key
      parameters:
      - description: Routing Key ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: api retrieve routing key
      tags:
      - Routing Keys
    put:
      consumes:
      - application/json
      description: api update routing key
      parameters:
      - description: Routing Key ID
        in: path
        name: id
        required: true
        type: string
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/schema.RoutingUpdateParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: api update routing key
      tags:
      - Routing Keys
swagger: "2.0"
